### PR TITLE
Auth Client & Web3Wallet

### PR DESCRIPTION
**Pull request by gigajuwels**
This features adds an auth client & Web3Wallet. Unit tests have been added for all new code

### CODE REVIEW

**Comment by formatCvt** [comment]
Hi! Thanks for PR but isn't working for me. QR code scan result have no response (Trust wallet app) until I've change AuthPayload property `Type` from `Cacao.CacaoHeader` to `string` with value "eip4361". But with this change auth result parsed incorrectly. How we can fix this?

**Comment by formatCvt** [comment]
@gigajuwels bump :)

**Comment by formatCvt** [comment]
i've get working version finally, there are problems with signed message restoration in FormatMessage function

**Comment by formatCvt** [comment]
my changes is here https://github.com/formatCvt/WalletConnectSharp/commits/feat/web3wallet

**Review by Talhaali00 — APPROVED** [review]

**Pull request merged**
